name: main
on: 
  push:
  workflow_dispatch:
name: cleans, build and test app (mobile - android)
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: clean stale build and cache
      uses: ./action
      with:
        args: clean

    - name: install dependencies
      uses: ./action
      with:
        args: pub get

    - name: build apk
      uses: ./action
      with:
        args: build apk --release
        

    - name: Push new files to GitHub
      run: |
        git config --global user.email "indiamadhuraj@gmail.com"
        git config --global user.name "madhuraj0"
        git commit -m "build commit"
        git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git main --force
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        PAT: ${{ secrets.PAT }}
