name: build android apk
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - name: build
      run: |
          cd cinemon
          flutter pub get
          flutter build apk --release
          mkdir -p apk
          cp build/app/outputs/flutter-apk/app-release.apk apk/app-release.apk
          git add . apk/app-release.apk

    - name: Push new files to GitHub
      run: |
          git config --global user.email "indiamadhuraj@gmail.com"
          git config --global user.name "madhuraj0"
          git commit -m "build commit"
          git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git main --force
      env:
          GITHUB_ACTOR: ${{ github.actor }}
          PAT: ${{ secrets.PAT }}

